### PR TITLE
Release workflows

### PR DESCRIPTION
**Pull request by VukW**
PR allows to build wheels and create releases automatically.

- Developer pushes a commit with newer version (`medperf/cli/_version.py`) to `main` branch (or merges a PR)
- workflow generates artifacts `.tar.gz` and `.whl`
- workflow creates new tag `vX.Y.Z`
- workflow creates a github release (like [these](https://github.com/VukW/medperf/releases)) and attach artifacts
- wheel can be installed manually by pip: `pip install medperf-0.1.2-py3-none-any.whl`

Wheel contains a mlcube depentency in `git+https://...` format, so
1. mlcube would be installed properly;
2. this wheel cannot be uploaded to pypi

image
Screenshot how tagging works (here prs are merged with merge, not squash):
- first PR (`version 0.1.1`) bumps version, [release is created automatically](https://github.com/VukW/medperf/releases/tag/v0.1.1)
- second PR do not change the version, workflow sleeps
- third PR bumps version to 0.1.2, so new release [contains info about both PR-2 and PR-3](https://github.com/VukW/medperf/releases/tag/v0.1.2)

### CODE REVIEW

**Comment by aristizabal95** [comment]
Would be great to have a check that ensures any PR that goes to main has a higher version value than the current one

**Comment by VukW** [comment]
> Would be great to have a check that ensures any PR that goes to main has a higher version value than the current one

Done!
1. https://github.com/VukW/medperf/pull/6 - if PR contains lower version, check fails https://github.com/VukW/medperf/actions/runs/8802318402/job/24157727747?pr=6
2. https://github.com/VukW/medperf/pull/7 - if PR doesn't change the version, check passes https://github.com/VukW/medperf/actions/runs/8802321894/job/24157738978?pr=7
3. https://github.com/VukW/medperf/pull/8 - if PR increases version, check passes https://github.com/VukW/medperf/actions/runs/8802326972/job/24157756310?pr=8

**Review by aristizabal95 — COMMENTED** [review]
Looks good! Did you write the code for release.yml? Or found it somewhere else? If taken from another source its best to add a comment indicating the source, to keep track of external authorship of things

**Comment by VukW** [comment]
@aristizabal95 the authorship belongs 75% to chatGPT / 25% to me 😁 But as far as I know bot does not insist on its authorship:)

**Comment by aristizabal95** [comment]
I see haha! I thought it could have come from another source due to the text with emojis, but forgot that LLMs are thing for a second 🤣

**Pull request merged**
